[WIP] PerpLeverageModule
SetProtocol/set-protocol-v2 pull request #158
Opened 2021-11-01 16:19 UTC by cgewecke

2021-11-03 13:07 UTC, rootulp commented on contracts/interfaces/external/perp-v2/IClearingHouse.sol
> +        // Q2B + exact input, want more output base as possible, so we set a lower bound of output base
Disregard. Based on `contracts/protocol/modules/PerpV2Module.sol`, it looks like B2Q = Base to Quote

2021-11-03 13:29 UTC, Alpha-Guy commented on contracts/interfaces/external/perp-v2/IAccountBalance.sol
> +pragma solidity 0.6.10;
Having multiple compiler versions makes it difficult to integrate other tools. For example, auto-compilation and testing flow might break by doing so.
Tagging @cgewecke, for a better summary of the pros and cons.

2021-11-03 13:50 UTC, Alpha-Guy commented on contracts/protocol/integration/lib/PerpV2.sol
> +    function getDepositCalldata(
Let's add javadocs here for better clarity. The goal is to provide enough context to a reader so that he/she doesn't have to go back to perp contracts/docs.
Copy and pasting javadocs from Perp contracts and adding any required modifications, would be enough.

2021-11-03 13:50 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2Module.sol
> +    function withdraw(
Do we need this function? If all it does is convert units to notional quantity and invoke the library.
The goal is to keep the module lean and clean, and any additional helper methods can be abstracted away in a viewer contract.
Same applies for `deposit()`.

2021-11-03 13:54 UTC, Alpha-Guy commented on contracts/interfaces/external/perp-v2/IClearingHouse.sol
> +        uint160 sqrtPriceLimitX96;
`X96` = × 2^96.
In words, multiplied by `2 ^ 96`.

2021-11-03 16:31 UTC, bweick commented on contracts/protocol/modules/PerpV2Module.sol
> +    mapping(ISetToken => address[]) public positions;
Let's add a note to be clear whether these are virtual tokens in the Perp ecosystem or whether they are the ERC20s they represent

2021-11-03 16:31 UTC, bweick commented on contracts/protocol/modules/PerpV2Module.sol
> +        address _baseToken,
Don't we want this to be a quote token so that we know which quote we are selling for base?

2021-11-03 16:31 UTC, bweick commented on contracts/protocol/modules/PerpV2Module.sol
> +        uint256 newDefaultTokenUnit = _setToken
Ideally here we can use `Position.calculateAndEditDefaultPosition`, we would need to save to memory the collateral balance from before depositing

2021-11-03 16:31 UTC, bweick commented on contracts/protocol/modules/PerpV2Module.sol
> +        uint256 newDefaultTokenUnit = _setToken
Same here as in `deposit`

2021-11-03 16:31 UTC, bweick commented on contracts/protocol/modules/PerpV2Module.sol
> +        setCollateralToken(_setToken, _collateralToken);
Let's make an internal version of this function, `_setCollateralToken`, and just call it in `setCollateralToken` with `external` vis and just internally here.

2021-11-03 16:31 UTC, bweick commented on contracts/protocol/modules/PerpV2Module.sol
> +    function _validateNewCollateralAsset(ISetToken _setToken, IERC20 _asset) internal view {
Think we also want to require that all collateral has been withdrawn from Perp here too

2021-11-03 16:31 UTC, bweick commented on contracts/protocol/modules/PerpV2Module.sol
> +        withdraw(_setToken, protocolFeeUnits);
Let's add a check to make sure we aren't withdrawing 0 units

2021-11-03 22:01 UTC, rootulp commented on contracts/interfaces/external/perp-v2/IClearingHouse.sol
> +        uint160 sqrtPriceLimitX96;
Thanks for sharing! Sorry for my naive questions:
1. What's the significance of 2 ^ 96 in this context?
2. Given we're not on Solidity 0.8.0 in this contract, should we be concerned about overflows and use [SafeMath](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/math/SafeMath.sol)?

2021-11-04 14:37 UTC, cgewecke commented on contracts/protocol/integration/lib/PerpV2.sol
> +    function getDepositCalldata(
Yes definitely :)

2021-11-04 14:53 UTC, cgewecke commented on contracts/protocol/modules/PerpV2Module.sol
> +    function withdraw(
Would this belong in a viewer contract though? 

My thinking about this part of the API is that methods like `engage` will call deposit and then lever to specify an amount of baseToken to buy, establishing the initial margin ratio between vault holdings and position size. 

Subsequent leverage ratio adjustments will  buy/sell baseTokens without depositing or withdrawing anything.

`withdraw` would be the final step if a manager wanted to close out the external position and re-allocate to another asset. 

@Alpha-Guy wdyt?

2021-11-04 15:05 UTC, cgewecke commented on contracts/protocol/modules/PerpV2Module.sol
> +        address _baseToken,
We discussed this further in a meeting ... the quote asset has a fixed identity (USDC) and the trade strategy implemented here is using Perp's exactIn / exactOut parameter to toggle whether the baseToken amount an output (when for ex: long:buying) or an input (when for ex: long:selling).

2021-11-04 15:28 UTC, cgewecke commented on contracts/interfaces/external/perp-v2/IAccountBalance.sol
> +pragma solidity 0.6.10;
> If this contract is a module which gets deployed independently, is it feasible to use 0.8.x?

All of its contract dependencies would need their pragmas adjusted (they're pinned). And modules share core contracts so this would entail changes across the code base. To upgrade to a new Solidity version I think we'll need to do the entire repo at once, as a separate step.

2021-11-04 15:39 UTC, cgewecke commented on contracts/interfaces/external/perp-v2/IClearingHouse.sol
> +        uint160 sqrtPriceLimitX96;
All of this sqrt stuff comes from UniswapV3. There a nice explanation of the format [in their docs, here][1]. 

We (and Perp) are using Uniswap's [Math libs][2] to handle these numbers ... definitely worth noting it's an external dependency we're making correctness assumptions about.  

[1]: https://docs.uniswap.org/sdk/guides/fetching-prices#understanding-sqrtprice
[2]: https://docs.uniswap.org/protocol/reference/core/libraries/FullMath

2021-11-04 15:40 UTC, cgewecke commented on contracts/protocol/modules/PerpV2Module.sol
> + * @title AaveLeverageModule
Thanks!

2021-11-14 21:58 UTC, bweick commented on contracts/protocol/integration/lib/PerpV2.sol
> +    function getDepositCalldata(
Bump here on some javadocs

2021-11-15 00:25 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        require(perpVault.getBalance(address(_setToken)) == 0, "Existing collateral balance");
`getBalance` returns the amount of collateral the Set has in the `Vault`?

2021-11-15 00:25 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     *         + USDC quote asset position size (10**18).
Is this the value of the `baseToken` in USDC? or the total outstanding `quote` position? Seems like if it's the latter it shouldn't vary on a per asset basis

2021-11-15 00:25 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function getPositionInfo(ISetToken _setToken) public view returns (PositionInfo[] memory) {
I think we should expose an endpoint that also returns the positionUnits for each perp position. Make this `getPositionNotionalInfo` and maybe another that is `getPositionUnitInfo`. I imagine the unit info may be helpful for our front end as well as potentially integrators since they have to submit `lever` and `delever` calls in unit terms.

2021-11-15 00:25 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // TODO: Update externalPositionUnit for collateralToken ?
We need to here since we may be opening an external position

2021-11-15 00:25 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // TODO: Update externalPositionUnit for collateralToken ?
We'd want to update this in cases where the manager calls `withdraw` in case we are zeroing out the position

2021-11-15 00:25 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // require collateral is a default component on SetToken
Not sure we need to validate this unless we have a function that sets the new collateral and atomically deposits (which I don't believe we do)

2021-11-15 19:48 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256[] memory adjustments = new int256[](1);
We want this to map to the order of the components array. I need to update the javadocs to make that clear.

2021-11-15 19:48 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256[] memory adjustments = new int256[](1);
We want this to map to the order of the components array. I need to update the javadocs to make that clear.

2021-11-15 19:48 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            ActionInfo memory actionInfo = _createAndValidateActionInfo(
I think this function converts the `basePositionUnit` to notional so we shouldn't do it beforehand. Unless we call `_createAndValidateActionInfoNotional`

2021-11-15 19:48 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +                0
If we're selling the `baseToken` to short does this need to be `MAX_UINT_256`?

2021-11-15 19:48 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Calculate current leverage
If we have multiple `baseToken` positions I think the current leverage will be influenced by previous trades, we may want to calculate this before executing any trades

2021-11-15 19:48 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function _executeModuleIssuanceHook(
Is it possible to restructure this so that we calculate the current leverage ratio first? From there we can imply some amount of vUSDC necessary to execute trades at the current spot price. Then we execute all the trades, sum the amount of vUSDC required to execute them and the difference between that and the implied amount is equal to slippage?

2021-11-15 19:48 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        return _abs(usdcAmountIn.preciseDiv(_setTokenQuantity.toInt256()));
Just noting here that we would want to then subtract the current position unit in order to provide the diff

2021-11-15 19:48 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            ActionInfo memory actionInfo = _createAndValidateActionInfo(
Ditto to comments above on using units vs notional and setting the trade limit

2021-11-15 19:55 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    IERC20 public collateralToken;
It's set via `perpVault.getSettlementToken() ` and `perpVault` is immutable

When I tried initializing this in the constructor I got this error:

```
Immutable variables cannot be read during contract creation time, which means they cannot be read in the constructor or any function or modifier called from it.
```

2021-11-15 20:27 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +                0
Ooooh. Good thing to flag...

The Perp [comments in IClearingHouse][1] say:
```
  // B2Q + exact input, want more output quote as possible, so we set a lower bound of output quote
  // B2Q + exact output, want less input base as possible, so we set a upper bound of input base
  // Q2B + exact input, want more output base as possible, so we set a lower bound of output base
  // Q2B + exact output, want less input quote as possible, so we set a upper bound of input quote
  // when it's 0 in exactInput, means ignore slippage protection
  // when it's maxUint in exactOutput = ignore
  // when it's over or under the bound, it will be reverted
```
The configuration is set in `_createActionInfo` like this and `0` maps to oppositeAmountBound

https://github.com/SetProtocol/set-protocol-v2/blob/d9f0a774850632a2b56a2cda5e9b468d88dd9183/contracts/protocol/modules/PerpV2LeverageModule.sol#L982-L993

Am interpreting this like: 
+ When short, exactInput == true, (ignore)
+ When long, exactOutput == true and direction is Q2B ... were buying an exact amount of vETH (positive) for an unknown amount of vQuote (negative) and zero is the vQuote upper bound.  


[1]: https://github.com/SetProtocol/set-protocol-v2/blob/d9f0a774850632a2b56a2cda5e9b468d88dd9183/contracts/interfaces/external/perp-v2/IClearingHouse.sol#L28-L35

2021-11-15 20:34 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Calculate current leverage
Yeah you're right, this isn't being done correctly at all.

2021-11-15 20:41 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            ActionInfo memory actionInfo = _createAndValidateActionInfo(
This is misnamed. It should be `baseTradeQuantityUnit` ... it's the basePositionUnit * mintQuantity.

2021-11-15 20:49 UTC, bweick commented
Let's make sure we test issuance scenarios where we have inverse positions, multiple positions, an inverse and long position, etc

2021-11-16 18:17 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        require(perpVault.getBalance(address(_setToken)) == 0, "Existing collateral balance");
Yes, exactly.

2021-11-16 18:30 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // require collateral is a default component on SetToken
All collateral setting logic was removed in af8068e

2021-11-16 18:35 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     *         + USDC quote asset position size (10**18).
This is the amount of notional quote backing the base position. For example if a set is long 1 vETH and 1 vBTC and 
+ vETH price = 10 USDC 
+ vBTC price = 20 USDC

...the positions will look like
```js
{
  baseToken: vETHAddress
  baseBalance: 1  (* 10^18)
  quoteBalance: -10.123 * (10^18 ) // includes slippage incurred while putting the position on
},
{
  baseToken: vETHAddress
  baseBalance: 1  (* 10^18)
  quoteBalance: -20.123 * (10^18 ) 
},
```

There's also a Perp protocol getter for the account-wide quote balance at: [Perp.AccountBalance.getNetQuoteBalance][1] though.

[1]: https://github.com/perpetual-protocol/perp-lushan/blob/016bd51f66ba4e1f5b107f83341c48af7b689901/contracts/AccountBalance.sol#L274

2021-11-16 18:47 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            sqrtPriceLimitX96: 0,
This is a way of filling the trade up to a post trade price limit without reverting. Setting it to zero turns it off.

The Perp comments in [IClearingHouse.sol][1] say:
```
// When B2Q: the price cannot be less than this value after the swap
// When Q2B: The price cannot be greater than this value after the swap
// Fill the trade until it reach the price limit instead of reverted
// When it's set to 0, it will disable price limit entirely regardless of B2Q or Q2B
```
[1]: https://github.com/perpetual-protocol/perp-lushan/blob/016bd51f66ba4e1f5b107f83341c48af7b689901/contracts/interface/IClearingHouse.sol#L49-L54

2021-11-16 19:11 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    // Mapping of SetTokens to an array of virtual token addresses the Set has open positions for.
Looked through the Perp contracts and it doesn't seem like there's a registry for that. The baseTokens are initialized with a chainlink price feed address. But the variable itself is `internal` .... it looks like the mapping will need to be maintained off chain. 

https://github.com/perpetual-protocol/perp-lushan/blob/d4b926366806f5f8075806fb71a69d50543e7447/contracts/BaseToken.sol#L16-L29

2021-11-17 05:12 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            int256 slippageQuantity = deltaQuote.toInt256().sub(idealDeltaQuote);
Would this always result in a negative number if there's slippage? But we add it to the `usdcAmountIn` below, which reduces the amount of USDC an issuer has to pay when it should be increasing?

2021-11-17 05:12 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            usdcAmountIn = usdcAmountIn.add(slippageQuantity.add(idealDeltaQuote.preciseDiv(currentLeverage)));
I think if we have a long perp and a short perp position that net each other out we could end up in a situation where someone is required to only pass in the slippage of the trades here? Since the `idealDeltaQuote` for each will cancel out

2021-11-17 05:12 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            usdcAmountIn = usdcAmountIn.add(slippageQuantity.add(idealDeltaQuote.preciseDiv(currentLeverage)));
The leverage ratio calculations use absolute value but we don't do that here until later on line 759. We made need to do that earlier

2021-11-17 14:39 UTC, cgewecke commented on contracts/protocol/integration/lib/PerpV2.sol
> +    function getDepositCalldata(
Added in 3764b69

2021-11-17 14:39 UTC, cgewecke commented on contracts/protocol/modules/PerpV2Module.sol
> +    function withdraw(
We discussed this in chat ... think this is resolved.

2021-11-17 14:44 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     *         + USDC quote asset position size (10**18).
This is tracking the quote added to the book at the time base was bought or sold. For short it would look like this, with slippage paid in less-quote-received
```js
{
  baseToken: vETHAddress
  baseBalance: -1  (* 10^18)
  quoteBalance: 9.987 * (10^18 ) // includes slippage incurred while putting the position on
}
```

2021-11-17 14:46 UTC, cgewecke commented on contracts/protocol/modules/PerpV2Module.sol
> +    function _validateNewCollateralAsset(ISetToken _setToken, IERC20 _asset) internal view {
We removed all collateral adding logic in af8068e.

2021-11-17 14:48 UTC, cgewecke commented on contracts/protocol/modules/PerpV2Module.sol
> +        uint256 newDefaultTokenUnit = _setToken
Fixed in e9b35d6

2021-11-17 14:48 UTC, cgewecke commented on contracts/protocol/modules/PerpV2Module.sol
> +        uint256 newDefaultTokenUnit = _setToken
Fixed in e9b35d6

2021-11-17 14:51 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        uint256 oppositeAmountBound;    // vUSDC receive quantity bound (see `_createAndValidateActionInfoNotional` for details)
Yes, that's right. Clarified this comment in 2e71bcb

2021-11-17 14:53 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            ? _deltaQuote.toInt256() - idealDeltaQuote
Using SIgnedSafeMath everywhere with 9a8182f

2021-11-17 14:54 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        require(_actionInfo.amount > 0, "Amount is 0");
Removed this function and moved check (reformatted as suggested) in: 4fd076e

2021-11-17 14:56 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // TODO: Update externalPositionUnit for collateralToken ?
Added note to javadocs about this in 6b8f27e

2021-11-17 14:56 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // TODO: Double-check deltas? Can we trust oppositeBoundAmount?
Added note to javadocs about this in 6b8f27e

2021-11-17 14:58 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +
Used the preciseMulCeil approach in _withdraw in 066e5de

2021-11-17 15:01 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256[] memory adjustments = new int256[](1);
This is fixed in f5cfd50

2021-11-17 15:01 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256[] memory adjustments = new int256[](1);
Fixed in f5cfd50

2021-11-17 15:03 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Calculate current leverage
Leverage moved outside the loop in 7ba9a90

2021-11-17 15:05 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        return _abs(usdcAmountIn.preciseDiv(_setTokenQuantity.toInt256()));
Diff is being returned with: f5cfd50

2021-11-17 15:11 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            ActionInfo memory actionInfo = _createAndValidateActionInfo(
Resolved this in: 7ba9a90. 

Only Lever/Delever have their position unit inputs converted to notional quantities in _createActionInfo now, with the calling context is signalled by a flag passed to that method.

The `baseTradeNotionalQuantity` passed to _createActionInfo here is not additionally modified (except by being converted to an absolute value.

2021-11-17 17:18 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function delever(
Per @richardliang's question I do wonder if it makes sense to limit it so that you can't delever past 0, and also make it so that you can't accidentally lever up by sending in the wrong sign. I can't help but feel this usage is a little wonky.

Probably some similar type of constraints need to be considered for `lever` (ie making sure `lever` is always either opening or adding to a position)

2021-11-17 21:10 UTC, cgewecke commented on contracts/protocol/modules/PerpV2Module.sol
> +    mapping(ISetToken => address[]) public positions;
d75d9b3

2021-11-17 21:19 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * | Action |  Type | isB2Q | Exact In / Out | Amount    | Recieve Token | Receive Description         |
> So if _notionalBaseTokenQuantity is positive then it means that _notionalQuoteReceiveQuantity is a maximum and vice versa it's a minimum?

Yes. When base is negative we request a minimum amount of positive quote  (to offset the debt side) and slippage is paid by receiving less quote. 

When base is positive we set a maximum amount of quote debt we're willing to take on and slippage is paid in negative quote. 

Changed the language in the table to talk about increasing position size / decreasing position size.

2021-11-17 21:24 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function delever(
We discussed this further in a meeting (Nov 17) and Richard proposed that we consolidate these methods into a single `trade` function (identical to lever) and let the manager handle long/short boundary concerns.

2021-11-18 01:22 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function delever(
9dc7137

2021-11-18 01:33 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function delever(
This is handled by changing `lever`/`delever` to just a plain `trade` interface

2021-11-18 01:36 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    IERC20 public collateralToken;
This may make sense to just pass in then, instead of get from perp. Some minor gas savings but I think worth it

2021-11-18 03:35 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        address[] memory components = _setToken.getComponents();
Refactored in 38124d6

2021-11-18 03:36 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        address[] memory components = _setToken.getComponents();
Refactored in 38124d6

2021-11-18 03:37 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        require(found, "Perp collateral token is not component");
Made tolerant in 38124d6. The new logic returns empty arrays of SetToken.components length if collateral token is not a component

2021-11-18 03:37 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        require(found, "Perp collateral token is not component");
Made tolerant in 38124d6. The new logic returns empty arrays of SetToken.components length if collateral token is not a component

2021-11-18 04:33 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // TODO: Add storage variants of contains, indexOf to AddressArrayUtils ?
Went with `positions[_setToken].contains` in 8b28951

2021-11-18 05:24 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        _deposit(_setToken, usdcTransferInQuantityUnits);
This change is made in: 644f712

Just a note: as written, all deposits update the `defaultPositionUnit`.  And only the external version of `deposit` updates the externalPositionUnit.

In turn, only `withdrawAndUpdateState` (called by the external version of `withdraw`) updates the defaultPositionUnit and the externalPositionUnit. 

`accrueFee` and `componentRedeemHook` withdraw without updating the defaultPositionUnit because those funds are immediately forwarded to other recipients so there's no change.

2021-11-18 05:25 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        _withdraw(_setToken, usdcTransferOutQuantityUnits, false);
644f712 (See comment above)

2021-11-18 05:29 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            int256 slippageQuantity = deltaQuote.toInt256().sub(idealDeltaQuote);
This was definitely wrong. Addressed in e940fce

2021-11-18 16:32 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 pendingFundingPayments = perpExchange.getAllPendingFundingPayment(address(_setToken));
Have added tables to the javadocs for this method describing the different ways owedRealizedPnl and pendingFunding can be positive or negative in: 6b7efae

2021-11-18 16:33 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        (int256 owedRealizedPnl, ) = perpAccountBalance.getOwedAndUnrealizedPnl(address(_setToken));
Have added tables to the javadocs for this method describing the different ways owedRealizedPnl and pendingFunding can be positive or negative in: 6b7efae

2021-11-18 16:34 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        uint256 usdcTransferInQuantityUnits = _setTokenQuantity.preciseMul(externalPositionUnit.toUint256());
Fixed in fd2165c

2021-11-18 16:35 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    IERC20 public collateralToken;
Made suggested change in: caa0e8e

2021-11-18 16:36 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        _deposit(_setToken, _collateralQuantityUnits);
Added zero check in: 0c0ddfa

2021-11-18 18:29 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function getPositionInfo(ISetToken _setToken) public view returns (PositionInfo[] memory) {
Added/renamed getters to: `getPositionUnitInfo` and `getPositionNotionalInfo` in 9303f91

2021-11-18 18:59 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function _formatCollateralToken(uint256 amount, uint8 decimals) internal pure returns (uint256) {
Added dev doc comments for this and the other formatters in 9525ace

2021-11-18 21:15 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            totalPositionNetValue = totalPositionNetValue.add(
We need this to be absolute value otherwise could end up with a negative account leverage

2021-11-18 21:16 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function _getCurrentLeverageAndSpotPrices(
We should start referring to this as account leverage not leverage ratio. I think we need to make that change throughout the contract

2021-11-21 13:57 UTC, Alpha-Guy requested changes
The current implementation looks really good to me. We are on the right path. Feel free to let me know if you think some of my suggestions are not worth implementing. 

Suggestion: Let us add a very small description, everywhere we chose either between `preciseMul` or `preciseMulCeil`. Same for `preciseDiv` or `preciseDivCeil`.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            int256 basePositionUnit = positionInfo[i].baseBalance.preciseDiv(_setToken.totalSupply().toInt256());
Does it make sense to extract the common parts from module issue and redeem hooks, and put them in a `public sync()` functions. That way we would have to store the virtual position units on the module. What benefits would it serve?

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    {
There are a few things that I would suggest changing in this function (Note: same applies to the `_withdrawAndUpdateState` function.
1. Starting with the name, "update state" is a bit vague name, and doesn't convey what's happening, so I would avoid it.
2. I would instead, break the function into two internal function, and let each do only one thing.
I suggest, removing this function, and instead do stuff in the public function.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            _calculateExternalPositionUnit(_setToken),
We do not need this function. Because 
1. We have clearly stated above, that none should rely on the external position unit set by this module.
2. But, if we do want to set a value, then I think it should utilize the same calculations as the issuance one, with the amount to trade = 0.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            _calculateExternalPositionUnit(_setToken),
Same as above.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * | ---------------------------------------------------------------------------------------------------------|
Let's break down this table into two sub-tables differentiating the `long` and `short` positions. Similar to how we have in the `trade()` function.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        if (_isLeverOrDelever) {
Let's have two internal functions, `_createAndValidateActionInfo` and `_createAndValidateActionInfoNotional`. The `_createAndValidateActionInfo` can call the other function, passing the notional amounts. It's not right to have a parameter represent both `units` and `quantity` at the same time.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            isExactInput: isShort,
Let's add columns in the table, explicitly indicating the relationship between `isB2Q`, `isExactInpt` and `isShort`.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * | --------------------------------------- |
Love these javadocs.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function _formatCollateralToken(int256 amount, uint8 decimals) internal pure returns (int256) {
All these `_xxxCollateralToken` functions can instead be renamed to `_xxxPreciseUnitxxx`, to indicate they are translating the value to a 10e18 multiple. Also, these functions are not specific to collateral token, hence having collateral token in the name is unnecessary.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function _abs(int x) internal pure returns (int) {
+1. Best method to resolve this would be to search for an existing library function (either in openZeppelin or BoringCrypto repos), which does this.

2021-11-21 13:57 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function _formatCollateralToken(int256 amount, uint8 decimals) internal pure returns (int256) {
Adding to this, we should avoid any raw `mul` or `div` calls. There would be a library or utility function that already does this. If not then, let's write one, making sure no overflows or other gotchas.

2021-11-21 16:46 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 externalPositionUnit = _setToken.getExternalPositionRealUnit(address(_component), address(this));
Let, USDC be a default position unit, an external position unit on two modules, perp and A, and debt position unit on module B.
Then, in the current DIM, during issuance, componentIssueHook twice on each perp, A and B.

- first, with isEquity = true
- second, with isEquity = false
    - we should not open position during this call.

During redemption, componentRedeemHook, is called twice on each perp, A and B.
- first with isEquity = false.
-  we should not close position during this call.
    - second with is Equity = true.
   
Hence, we should allow, `componentIssueHook` to only be executed with `isEquity` is true, and `componentRedeemHook` when `isEquity` is false.

2021-11-21 16:46 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function moduleIssueHook(
Refer above comment.

2021-11-21 16:50 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    {
As per above, let us add a check to return if `isEquity` is true.

2021-11-21 16:51 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 externalPositionUnit = _setToken.getExternalPositionRealUnit(address(_component), address(this));
+1 great catch

2021-11-21 16:51 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 externalPositionUnit = _setToken.getExternalPositionRealUnit(address(_component), address(this));
Let us add a check to return if `isEquity` is false, and explain it in javadocs.

2021-11-21 16:53 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        if (_isLeverOrDelever) {
+1 to this

2021-11-21 17:14 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        bool /* isEquity */
As per above, let us add a check to return if `isEquity` is true.

2021-11-21 17:39 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Set USDC externalPositionUnit such that DIM can use it for transfer calculation
Similarly, `vUSDC` with `quote asset (e.g. vUSDC)`.

2021-11-21 18:14 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 externalPositionUnit = _setToken.getExternalPositionRealUnit(address(_component), address(this));
Fixed in [this](https://github.com/SetProtocol/set-protocol-v2/pull/158/commits/c87fea935552a8b2a6c41b31bb0354ff818d78f8) commit

2021-11-21 18:27 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        collateralToken = _collateralToken;
yeah the problem here is that we want to make them `immutable` and we can't query them from Perp and set them as `immutable`. So doing this instead.

2021-11-21 18:40 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        require(actionInfo.amount != 0, "Amount is 0");
Let's add this check somewhere before. Verify first, write last.

2021-11-21 18:46 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        uint256 initialCollateralPositionBalance = collateralToken.balanceOf(address(_setToken));
Using `balanceOf` here (and in the `depositAndWithdrawState`) allows the initialized Sets value to be drastically changed by anyone. This might open the Set to be used as a tool for exploiting the money markets it is listed on, similar to yUSDC vault in the compound hack.

2021-11-21 18:54 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    {
Are you suggesting that the position updates should just happen in a separate internal function instead of inline in this function?

2021-11-21 18:58 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            _calculateExternalPositionUnit(_setToken),
Well we need this update to happen when we call `deposit` in order to make sure the SetToken knows we now have an external position so `depositAndUpdateState` should only be called then. `_deposit` is used in all other places which doesn't update any state

2021-11-21 18:58 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            _calculateExternalPositionUnit(_setToken),
See above explanation

2021-11-21 19:01 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * | --------------------------------------- |
+1

2021-11-21 19:03 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function _formatCollateralToken(int256 amount, uint8 decimals) internal pure returns (int256) {
`.mul` and `.div` are `SafeMath` functions. Is there something else you're concerned about?

2021-11-21 19:06 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        uint256 initialCollateralPositionBalance = collateralToken.balanceOf(address(_setToken));
In this scenario it would be fine since we're using it for position setting. The logic in the position setting explicitly excludes any tokens that have been "airdropped". See [here](https://github.com/SetProtocol/set-protocol-v2/blob/f7fe16b63b6e5158ec84b37bcfe395890d4a5a38/contracts/protocol/lib/Position.sol#L256).

Good thing to be looking out for though

2021-11-21 19:09 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> + */
+1

2021-11-21 19:10 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    IERC20 public immutable collateralToken;
Yeah think right now the best we can do is just build for this implementation where USDC is the collateral.

2021-11-21 19:26 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function getSpotPrice(address _baseToken) public view returns (uint256 price) {
Changed [here](https://github.com/SetProtocol/set-protocol-v2/pull/158/commits/4220c82d4fedf2efd93341559d4501650ba11b2d)

2021-11-21 20:08 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * | ---------------------------------------------------------------------------------------------------------|
I think this framing is a little irrelevant now since we aren't using the `lever` and `delever` construct. We are just executing a trade.

2021-11-21 20:15 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        if (_isLeverOrDelever) {
Implemented [here](https://github.com/SetProtocol/set-protocol-v2/pull/158/commits/1fa5fcc790df616e6f8e0179d6401cd788a23ebd)

2021-11-21 20:20 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        require(actionInfo.amount != 0, "Amount is 0");
+1

2021-11-21 20:32 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function _formatCollateralToken(int256 amount, uint8 decimals) internal pure returns (int256) {
Made naming changes [here](https://github.com/SetProtocol/set-protocol-v2/pull/158/commits/3b580c5ae601d34b3cc57316ef7bdc13114770e6)

2021-11-21 22:42 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    function _getCurrentLeverageAndSpotPrices(
Changed in [this](https://github.com/SetProtocol/set-protocol-v2/pull/158/commits/5f0a0e46d0c356a915431a9f48f2bd5bb44e670f) commit

2021-11-21 22:43 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            int256 basePositionUnit = positionInfo[i].baseBalance.preciseDiv(_setToken.totalSupply().toInt256());
Can you expand a bit more on which changes you're thinking about?

2021-11-22 03:14 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        collateralToken = _collateralToken;
`immutable` variables can be assigned in the constructor. Regarding the vault itself, we can create a temp variable. So,
```
IVault _vault = IVault(_vault);
collateralToken = _vault.settlementToken();
....
// finally assign valut
perpVault = _vault;
```
We have used this method before in other modules, like ALM.

2021-11-22 04:51 UTC, Alpha-Guy requested changes

2021-11-22 04:51 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 totalPositionAbsoluteValue = 0;
Since this is an absolute value, let's change the type to `uint256`.

2021-11-22 04:51 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            (,uint256 deltaQuote) = _executeOrSimulateTrade(actionInfo, _isSimulation);
`(,uint256 deltaQuote) = isSimulation ? _simulateTrade(actionInfo) : _executeTrade(actionInfo)` is cleaner. And it also reduces the contract bytesize.

2021-11-22 05:18 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        (int256 owedRealizedPnl, ) = perpAccountBalance.getOwedAndUnrealizedPnl(address(_setToken));
This variable should be named `unRealizedPnl`, instead of `owedRealizedPnl`. The function name itself should be updated to `_calculateNetDiscount`. As 
1. the current name has `realized` in it, which is incorrect, as it is `unrealizedPnl`
2. the current name skips the fact that this function also takes funding into account.

2021-11-22 13:59 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        (int256 owedRealizedPnl, ) = perpAccountBalance.getOwedAndUnrealizedPnl(address(_setToken));
@sachin Do you mean its unrealized in the sense of not being cleared to the vault?

Perps naming convention seems to be to use `owedRealizedPnl` for pnl that is booked as a direct result of trading and I think they're drawing a distinction between "realized" and "settled", e.g pnl settled to the vault.

They also have a quantity called `unrealizedPnl` (the second return value of this tuple) where Pnl is calculated with reference to the oracle price. 

The (newest) getter code is [here in perp-lushan/AccountBalance.sol][1]:

> _calculateNetDiscount

Agree, that's probably better....

[1]: https://github.com/perpetual-protocol/perp-lushan/blob/main/contracts/AccountBalance.sol#L232-L251

2021-11-22 14:05 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            (,uint256 deltaQuote) = _executeOrSimulateTrade(actionInfo, _isSimulation);
Yeah makes sense ... if we do this we also need to move the response normalization for quoter.swap into simulate trade.

2021-11-22 14:09 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 totalPositionAbsoluteValue = 0;
Wouldn't we have to un-convert in a bunch of places immediately below here to do the arithmetic with int256's? (Idk if this function is even being kept though...)

2021-11-22 16:41 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        (int256 owedRealizedPnl, ) = perpAccountBalance.getOwedAndUnrealizedPnl(address(_setToken));
yeah, sorry about that, I got a bit confused, had to revisit perp codebase. The correct logic to handle PnLs LGTM.

2021-11-22 17:03 UTC, Alpha-Guy submitted a review, later dismissed
Reviewed tests in  `PerpV2LeverageModule.spec.ts`. Few small suggestions:

2021-11-22 17:03 UTC, Alpha-Guy commented on test/protocol/modules/perpV2LeverageModule.spec.ts
> +
Need a test case for when `withdraw()` is called when a SetToken lever position exists.

2021-11-22 17:03 UTC, Alpha-Guy commented on test/protocol/modules/perpV2LeverageModule.spec.ts
> +          usdcTransferInQuantity = usdcTransferInQuantity = await calculateUSDCTransferIn(
Remove extra declaration.

2021-11-22 17:58 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            ERC20(address(collateralToken)).decimals()
Instead of doing the same at multiple places, we can store (cache) the decimals. Similar to [this](https://github.com/perpetual-protocol/perp-lushan/blob/d4549a042d88b2d6428b24d9637b3b52c4a4a65d/contracts/interface/IVault.sol#L34)

2021-11-22 18:00 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    {
yups.

2021-11-22 18:03 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            _calculateExternalPositionUnit(_setToken),
Dropping the observation that, the latest issuance hook formulas are equal to the above formulas when the amount to trade is 0, aka we use only the spot price and zero slippage.

2021-11-22 18:07 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            uint256 usdcTransferInNotionalQuantity = _setTokenQuantity.preciseMulCeil(externalPositionUnit.toUint256());
Resurfacing one of my first comments, can we add a very small one-two line explanation every time we choose between  `preciseMul` or `preciseMulCeil`. 
Same for `preciseDiv` or `preciseDivCeil`.
And same for `uint256` and `int256`.

2021-11-22 23:54 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            uint256 usdcTransferInNotionalQuantity = _setTokenQuantity.preciseMulCeil(externalPositionUnit.toUint256());
Added comments for preciseMulCeil here: 515a29e

I think commenting int256 is going to add a lot of noise to the code tbh but maybe that's a good idea.

2021-11-22 23:54 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            ERC20(address(collateralToken)).decimals()
This fix is in 4de0362

2021-11-22 23:55 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        collateralToken = _collateralToken;
Added in 4de0362

2021-11-22 23:56 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        (int256 owedRealizedPnl, ) = perpAccountBalance.getOwedAndUnrealizedPnl(address(_setToken));
Renamed method to _calculatedNetDiscount: 6c0739f

2021-11-22 23:56 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            (,uint256 deltaQuote) = _executeOrSimulateTrade(actionInfo, _isSimulation);
Refactored this in: 6be0a29

2021-11-23 00:05 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            uint256 usdcTransferInNotionalQuantity = _setTokenQuantity.preciseMulCeil(externalPositionUnit.toUint256());
We really use `preciseMulCeil` there because when we're transferring in equity amounts we determine how much to transfer in by doing `positionUnit.preciseMulCeil(_issueQuantity)` so this is just making sure that all tokens get deposited and there isn't any dust left behind

2021-11-23 00:07 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Use preciseMulCeil here to ensure correct collateralization if there are rounding errors.
I'm not sure we want to use `Ceil` here I think we just want this to be normal

2021-11-23 00:08 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Use preciseMulCeil here to make sure we sweep out rounding dust when manager invokes withdraw
I think we want this to just be `preciseMul`. This could actually be the reason for withdrawals failing sometimes. There's the potential to try to withdraw more than we actually have when doing this. That would lead to reverts I would assume

2021-11-23 00:09 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Use preciseMulCeil here to make sure we sweep out rounding dust when manager invokes withdraw
Right that definitely makes sense....

2021-11-23 00:16 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Use preciseMulCeil here to make sure we sweep out rounding dust when manager invokes withdraw
b1fa634

2021-11-23 00:16 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Use preciseMulCeil here to ensure correct collateralization if there are rounding errors.
b1fa634

2021-11-23 00:55 UTC, cgewecke commented on test/protocol/modules/perpV2LeverageModule.spec.ts
> +
9441380

2021-11-23 00:56 UTC, cgewecke commented on test/protocol/modules/perpV2LeverageModule.spec.ts
> +
9441380

2021-11-23 00:56 UTC, cgewecke commented on test/protocol/modules/perpV2LeverageModule.spec.ts
> +          usdcTransferInQuantity = usdcTransferInQuantity = await calculateUSDCTransferIn(
01d8dc8

2021-11-23 00:57 UTC, cgewecke commented on test/protocol/modules/perpV2LeverageModule.spec.ts
> +  describe("#trade", () => {
This makes sense ... I haven't done this yet because it will substantially re-order the file really and there's an open PR pointing here.

2021-11-23 04:28 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            .preciseDiv(_setToken.totalSupply().toInt256());
Using absolute value here when calculating the positionValue isn't right for the short case ... a positive netQuote is added to a positive positionValue, inflating the unit. Think this needs to be like:

```solidity
for (uint i = 0; i < positionInfo.length; i++ ) {
    int256 spotPrice = getAMMSpotPrice(positionInfo[i].baseToken).toInt256();
    totalPositionValue = totalPositionValue.add(
        positionInfo[i].baseBalance.preciseMul(spotPrice)
    );
    totalPositionValue = totalPositionValue.add(
        positionInfo[i].quoteBalance
    );
}

int256 externalPositionUnitInPrecisionDecimals = totalPositionValue
    .add(accountInfo.collateralBalance)
    .add(accountInfo.owedRealizedPnl)
    .add(accountInfo.pendingFundingPayments)
    .preciseDiv(_setToken.totalSupply().toInt256());
```

2021-11-23 12:56 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // TODO: Double-check deltas? Can we trust oppositeBoundAmount?
@cgewecke any updates on this?

2021-11-23 13:06 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        collateralToken = _collateralToken;
We are fetching only the collateral token. As mentioned above, we can fetch others as well. Specifically these

> Collateral token, exchange, account balance and clearing house

2021-11-23 13:15 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // Use preciseMulCeil here to make sure we sweep out rounding dust when manager invokes withdraw
Yups, this is what I was trying to get out of by being explicit about why we are choosing between `preciseMul` and `preciseMulCeil`. It's just easier to catch hidden bugs this way.

2021-11-23 13:41 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            .preciseDiv(_setToken.totalSupply().toInt256());
Yes agreed. Need to change that. From perp's docs
```
positionValue = positionSize * vBaseIndexPrice`, and 
positionSize := >0, if long
                         <0, if short
                    = vBaseBalance
```

2021-11-23 14:12 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 closeRatio = baseTradeNotionalQuantity.preciseDiv(_positionInfo.baseBalance);
`closeRatio = abs(baseTradeNotional) / abs(baseBalance)`.
The current formula would lead to wrong results when `baseTradeNotional` and `baseBalance` have opposite signs.

2021-11-23 14:34 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        PositionNotionalInfo[] memory positionInfo = getPositionNotionalInfo(_setToken);
why not call `getPositionUnitInfo` here? Since we are calculating units in the for loop.

2021-11-23 15:34 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        PositionNotionalInfo[] memory positionInfo = getPositionNotionalInfo(_setToken);
Yes, this likely makes sense... it just wasn't updated when the positionUnitInfo method was added.

2021-11-23 15:40 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        PositionNotionalInfo[] memory positionInfo = getPositionNotionalInfo(_setToken);
Actually .... we use this PositionInfo.quoteBalance in `_getReducedOpenNotional` ... maybe this shouldn't change.

2021-11-23 15:40 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 closeRatio = baseTradeNotionalQuantity.preciseDiv(_positionInfo.baseBalance);
When would the sign be different?

2021-11-23 17:03 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
>              // Execute or simulate trade
Would just add note here that `deltaQuote` always returns a positive number

2021-11-23 18:53 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 closeRatio = baseTradeNotionalQuantity.preciseDiv(_positionInfo.baseBalance);
when we are flipping our position from long to short or vice-versa.

2021-11-23 19:09 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 closeRatio = baseTradeNotionalQuantity.preciseDiv(_positionInfo.baseBalance);
Was thinking we would flip our position via `trade`.... here we're replicating.

2021-11-23 21:23 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
>              // Execute or simulate trade
3f60553

2021-11-24 16:38 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 closeRatio = baseTradeNotionalQuantity.preciseDiv(_positionInfo.baseBalance);
Updated in b3785c6. Agree, following the perp formulas seems like the most conservative approach.

2021-11-24 16:41 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        collateralToken = _collateralToken;
Sorry, yes this completed in 4912c55

2021-11-24 17:14 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // TODO: Double-check deltas? Can we trust oppositeBoundAmount?
Let's delete this comment...I have note to address it in internal audit if we decide to do the check

2021-11-24 17:14 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * to the Perp vault prior to transfer.   // TODO: DOUBLE-CHECK THIS... and what are implications?
@cgewecke is there still a to do here?

2021-11-24 17:14 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * NOTE: Function will revert if there are any remaining collateral deposits in the PerpV2 vault.
Function will revert if there is greater than a position unit amount of USDC left in Perpetual

2021-11-24 18:10 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * NOTE: Function will revert if there are any remaining collateral deposits in the PerpV2 vault.
7beeff0

2021-11-24 18:12 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * to the Perp vault prior to transfer.   // TODO: DOUBLE-CHECK THIS... and what are implications?
No. 7beeff0

2021-11-24 18:12 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // TODO: Double-check deltas? Can we trust oppositeBoundAmount?
7beeff0

2021-11-24 20:14 UTC, bweick approved these changes

2021-11-24 20:26 UTC, cgewecke commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        // TODO: Double-check deltas? Can we trust oppositeBoundAmount?
This is flagged for the internal audit.

2021-11-24 20:31 UTC, merged