Perpetual issuance module added and associated mock updates.
SetProtocol/set-protocol-v2 pull request #185
Opened 2022-01-05 19:26 UTC by bweick

To Do:
[ ] Write `PerpProtocolIssuanceModule` that inherits `SlippageIssuanceModule` and adds getter for `getMaximumSetTokenIssueAmount` (that calls `PerpModule`)
[ ] Update associated interfaces and mocks
[ ] Write unit tests for `PerpProtocolIssuanceModule`
[ ] Add `getMaximumSetTokenIssueAmount` to `PerpModule`
[ ] Add units tests for `getMaximumSetTokenIssueAmount`
[ ] Add integration tests that use `PerpProtocolIssuanceModule` and test `getMaximumSetTokenIssueAmount` flow

# Code Review Processes
## New Feature Review
Before submitting a pull request for new review, make sure the following is done:
* Design doc is created and posted here: [Insert Link]
* Code cleanliness and completeness is addressed via [guidelines](https://app.gitbook.com/@setprotocol-1/s/set/smart-contract-engineering/sc-code-review-process)

README Checks
- [] README has proper context for the reviewer to understand what the code includes, any important design considerations, and areas to pay more attention to

Code Checks
- [] Add explanatory comments. If there is complex code that requires specific context or understanding, note that in a comment
- [] Remove unnecessary comments. Any comments that do not add additional context, information, etc. should be removed
- [] Add javadocs. 
- [] Scrub through the code for inconsistencies (e.g. removing extra spaces)
- [] Ensure there are not any .onlys in spec files

Broader Considerations
- [] Ensure variable, function and event naming is clear, consistent, and reflective for the scope of the code.
- [] Consider if certain pieces of logic should be placed in a different library, module

2022-01-12 12:49 UTC, Alpha-Guy requested changes
LGTM. Suggested minor improvements.

2022-01-12 12:49 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpProtocolIssuanceModule.sol
> + * The IssuanceModule is a module that enables users to issue and redeem SetTokens that contain default and
Nit: The PerpProtocolIssunaceModule enables users to issue ..

2022-01-12 12:49 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpProtocolIssuanceModule.sol
> + * @title PerpProtocolIssuanceModule
Why not name it `PerpV2IssuanceModule`? Just to be consistent with other contract names.

2022-01-12 12:49 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 partialAccountValue = accountInfo.collateralBalance
This variable can instead be called `totalCollateralValue`, as that is the term used to refer to the sum of these 3 values.

2022-01-12 12:49 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * @return  Struct containing important Perpetual Protocol addresses
Nit: Array of addresses containing important Perpetual Protocol addresses

2022-01-12 12:49 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            address(perpMarketRegistry)
Is it a good idea to return them in alphabetical order?

2022-01-12 12:49 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * @param  _baseToken)          Address of virtual token to price
Nit remove `)`

2022-01-12 12:49 UTC, Alpha-Guy commented on test/integration/perpV2LeverageSlippageIssuance.spec.ts
> +    });
Add tests for `usedCollateralRatio = 0` case.

2022-01-12 12:49 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> -        require(_setToken.totalSupply() > 0, "SetToken supply is 0");
Why remove these?

2022-01-12 12:49 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +     * totalSupply/usedCollateralRatio - totalSupply.
Suggest we should stick to only one formula in javadcos across `PerpIssuanceModule`, `IPerpLeverageModule` and `PerpLeverageModule` contracts.

2022-01-12 18:16 UTC, bweick commented on contracts/interfaces/IPerpV2LeverageModule.sol
> +     * leverage ratio is met. This amount is roughly equal to (maxLeverageRatio/currentLeverageRatio)*totalSupply.
Leaving note for myself...this javadoc needs to be updated

2022-01-12 18:17 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> -        require(_setToken.totalSupply() > 0, "SetToken supply is 0");
Bytecode size limits. Don't think the checks really add much from a security standpoint and removing them gets us under the limit

2022-01-12 20:27 UTC, bweick commented on contracts/protocol/modules/PerpProtocolIssuanceModule.sol
> + * @title PerpProtocolIssuanceModule
+1

2022-01-12 20:28 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        int256 partialAccountValue = accountInfo.collateralBalance
+1

2022-01-12 20:32 UTC, bweick commented on test/integration/perpV2LeverageSlippageIssuance.spec.ts
> +    });
I think that's sufficiently tested in the `PerpV2LeverageModule#getMaximumSetTokenIssueAmount` tests

2022-01-13 13:43 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +        returns (address[] memory vTokens, int256[] memory leverageRatios)
@bweick Can we modify this getter to also return the index Price of each virtual asset? The front end needs that value.

2022-01-13 19:42 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +            address(perpMarketRegistry)
I just returned in order of how we have them in the contract. Don't think alphabetical is necessarily super helpful one way or the other. Don't think that's an obvious pattern

2022-01-20 12:36 UTC, Alpha-Guy requested changes

2022-01-20 12:36 UTC, Alpha-Guy commented on contracts/interfaces/external/perp-v2/IIndexPrice.sol
> +interface IIndexPrice {
Let's rename this to `IBaseToken`

2022-01-20 12:36 UTC, Alpha-Guy commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +    ERC20 public immutable vQuoteToken;                             // Virtual Quote asset for PerpV2 (vUSDC)
Why is this not `IERC20`?

2022-01-20 12:36 UTC, Alpha-Guy commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +     * collateral as defined in PerpV2's docs: freeCollateral = min(totalCollateral, accountValue) - totalDebt * imRatio
Let's expand `imRatio` to `initial margin ratio`.

2022-01-20 12:36 UTC, Alpha-Guy commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +     * is less than totalCollateral when unrealizedPnl < 0 which gives us the following equations:
Rather than saying we know, let us just put the `accountValue` equation here.

2022-01-20 12:36 UTC, Alpha-Guy commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +     * of slippage divided by the imRatio from the availableDebt. We can then divide the availableDebtWithSlippage by
nit: remove of

2022-01-20 12:36 UTC, Alpha-Guy commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +     * @dev Returns the position unit for total collateral value as defined by Perpetual Protocol.
nit: Returns the total collateral value per set.

2022-01-20 12:36 UTC, Alpha-Guy commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +        assetInfo = new VAssetDisplayInfo[](positionsLength.add(1));
What if there is no vUSD?

2022-01-20 12:36 UTC, Alpha-Guy commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +                symbol: ERC20(position.baseToken).symbol(),
nit: IERC20

2022-01-20 15:31 UTC, Alpha-Guy requested changes

2022-01-20 15:31 UTC, Alpha-Guy commented on hardhat.config.ts
> +      allowUnlimitedContractSize: true,
Are we still using this?

2022-01-20 15:31 UTC, Alpha-Guy commented on contracts/mocks/protocol/module/DebtModuleMock.sol
> +    function getMaximumSetTokenIssueAmount(ISetToken _setToken) external view returns(uint256) {
It seems we are no longer using these. So, let's remove this and the `setIssuanceMaximum` funciton.

2022-01-20 15:51 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    IAccountBalance internal immutable perpAccountBalance;
Now that we are no longer hitting the bytecode size limit. I will suggest making these public. Or I can do it along with the ABDK audit fixes.

2022-01-20 15:53 UTC, Alpha-Guy commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> -        require(_setToken.totalSupply() > 0, "SetToken supply is 0");
Now that we are no longer hitting the bytecode size limit, I would suggest keeping this check, given that ABDK audit didn't suggest to remove it.

2022-01-20 17:36 UTC, bweick commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +        assetInfo = new VAssetDisplayInfo[](positionsLength.add(1));
there will always be vUSDC since it's the quote asset for the whole system. If no positions have been opened then it will just return 0

2022-01-20 17:37 UTC, bweick commented on hardhat.config.ts
> +      allowUnlimitedContractSize: true,
I'm fine leaving it. We do most of our testing on `--localhost` the only time we fall over the `hardhat` is when the size is too large

2022-01-20 17:38 UTC, bweick commented on contracts/protocol/modules/PerpV2LeverageModule.sol
> +    IAccountBalance internal immutable perpAccountBalance;
yeah I'm fine with that and deleting the getter. Let's make that change in the ABDK audit PR.

2022-01-20 18:15 UTC, Alpha-Guy commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +        assetInfo = new VAssetDisplayInfo[](positionsLength.add(1));
Brian in slack:
> I think we just want to provide the raw data. It's basically a db query
> they should then decide how they want to display it

2022-01-20 18:19 UTC, bweick commented on contracts/protocol-viewers/PerpV2LeverageModuleViewer.sol
> +        //                  = availableDebtWithSlippage / (totalAbsPositionValue / setTotalSupply)
`* totalSetSupply`

2022-01-20 18:20 UTC, Alpha-Guy approved these changes
Module-specific changes will be added along with the ABDK audit fixes. Rest LGTM.

2022-01-20 18:35 UTC, merged