PerpV2 Basis Trading Module
SetProtocol/set-protocol-v2 pull request #198
Opened 2022-03-02 16:17 UTC by 0xSachinK

2022-03-04 15:36 UTC, richardliang requested changes
As we discussed in DMs
* Performance fees should be a fee split vs a flat fee
* We can remove the `_trackSettledFunding` param in the `tradeAndTrackFunding` function

Only looked at the changelog in the issuance hooks and getRedemptionAdjustments. Will take another pass after these changes

2022-03-04 15:36 UTC, richardliang commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        _updateSettledFunding(_setToken, _trackSettledFunding);
If `_trackSettledFunding` is true, it would be very difficult to calculate the correct `_amount` to withdraw all settled funding right.

Maybe can create some better UX i.e. if _amount > settledFunding then withdraw settledFunding

2022-03-04 15:36 UTC, richardliang commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +            uint256 performanceFeeUnit = _getUpdateSettledFunding(_setToken)
Add more comments here to explain the calculations

2022-03-04 15:36 UTC, richardliang commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +            settledFunding[_setToken] = _getUpdateSettledFunding(_setToken);
Can inline this if statement

2022-03-04 15:36 UTC, richardliang commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +     * Values in the returned arrays map to the same index in the SetToken's components array.
Add a bit more context where/why this function is used

2022-03-04 15:36 UTC, richardliang commented on test/protocol/modules/perpV2BasisTradingModule.spec.ts
> +  describe("#trade", () => {
`tradeAndTrackFunding`

2022-03-04 18:30 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +contract PerpV2BasisTradingModule is PerpV2LeverageModule {
The naming is geared towards the product category it enables and it is easier to use this name across the rest of the tech stack. We had a very similar discussion last time, where we wrote DIMV2 and named it DIMV2, although other parts of the stack said it would have been easier had it just been called AaveIssuanceModule.
Also, PerpV2LeverageModuleV2 could be used for the module which supports multicollateral, and if we name this V2, we would have to name the next one V3, and it becomes tougher to manage down the line.

2022-03-04 18:33 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        _updateSettledFunding(_setToken, _trackSettledFunding);
Good suggestion.

2022-03-04 18:37 UTC, 0xSachinK commented on contracts/lib/UnitConversionUtils.sol
> +    function toPreciseUnitsFromDecimals(uint256 _amount, uint8 _decimals) internal pure returns (uint256) {
It is consistent with the other two function names, `fromPreciseUnitToDecimals`.

2022-03-06 20:12 UTC, bweick commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        if (performanceFee > 0) {
Feels like the fee should be a percentage of the fees accrued by the manager imo

2022-03-06 20:12 UTC, bweick commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        require(_settings.maxPerformanceFeePercentage < PreciseUnitMath.preciseUnit(), "Max fee must be < 100%");
<=

2022-03-06 20:12 UTC, bweick commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        // todo: Following call fetches pending funding payment across all markets. Should we change it?
What are the alternatives?

2022-03-06 20:12 UTC, bweick commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        // todo: call updateSettledFunding here?
should definitely accrue fees here

2022-03-07 14:32 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        if (performanceFee > 0) {
Fixed in [8376fb92](https://github.com/SetProtocol/set-protocol-v2/pull/198/commits/8376fb9210df683d5fa25115b61728aea3417e06).

2022-03-08 07:36 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        _updateSettledFunding(_setToken, _trackSettledFunding);
Added in [db0dd4](https://github.com/SetProtocol/set-protocol-v2/pull/198/commits/db0dd4ec2a1c36fdab64eb3172c909d28495287c)

2022-03-08 07:41 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +            return settledFunding[_setToken].sub(pendingFundingToBeSettled.abs());
Yeah the return zero at the end handles that case. (Assuming `settledFunding[_setToken]` doesn't go below zero.)

2022-03-08 09:51 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        _updateSettledFunding(_setToken, _trackSettledFunding);
The two other places where we are passing in `true` are module hooks. We always want to track settled funding in module hooks. Also, I can't pass in `_trackSettledFunding` as a parameter because then the functions wouldn't adhere to the `IModuleIssuanceHook` interface.

2022-03-08 11:49 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        // `trade` function has a redundancy check
Oh, `redundancy` was a typo. Edited it to:
<javascript>
// Calling a `nonReentrant` function from another `nonReentrant function is not supported.
// Hence, can't use `nonReentrant` here because `PerpV2LeverageModule#trade` function has a reentrancy check.
</javascript>

2022-03-08 12:50 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        // todo: call updateSettledFunding here?
If we do accrue fees here, then we should first withdraw all of it and absorb it as default position and then set `settledfunding[_setToken]` to zero (similar to how we do in withdrawAndAccrueFees). But I'm not sure if that is desirable, and is what the manager excepts to happen.

2022-03-08 14:38 UTC, richardliang requested changes
Pending Brian's comments

Let's make a decision on whether `settledFunding` can be negative

2022-03-08 14:38 UTC, richardliang commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        // Verrifies caller is manager. Verifies Set is valid, allowed and in pending state.
`Verifies`

2022-03-08 14:38 UTC, richardliang commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        // Calling a `nonReentrant` function from another `nonReentrant` function is not supported.
We can move this comment to the above javadocs

2022-03-08 17:01 UTC, bweick commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        // todo: call updateSettledFunding here?
In the past for things like this we always accrued fees. Though a) perhaps that's too opinionated of a stance, and b) in this case it actually updates the position state would could be a surprise so I'm ok forgoing it in this case

2022-03-08 18:16 UTC, bweick commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        if (pendingFundingToBeSettled > 0) {
Should make this `>= 0` right now if pending funding is 0 then it will return 0

2022-03-08 20:45 UTC, bweick commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        if (_notionalFunding > settledFundingInCollateralDecimals) {
Can we DRY this function up a bit? Put the logic for determining the `_notionalFunding` in its own function. Potentially the `collateralBalanceBeforeWithdraw` in there as well

2022-03-08 20:45 UTC, bweick commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        _setToken.calculateAndEditDefaultPosition(
Maybe group the state update logic together as well

2022-03-09 06:44 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        _updateSettledFunding(_setToken, _trackSettledFunding);
Good question. Realized it makes sense to auto-update it. 
Because for example, a manager can decide not to update settled funding when the pending funding is negative, which isn't a desirable outcome for investors.

2022-03-09 06:54 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        _updateSettledFunding(_setToken, _trackSettledFunding);
Fixed in [febb656](https://github.com/SetProtocol/set-protocol-v2/pull/198/commits/febb6562df08ceb0bda0a24bc210b5a13f0e85f0)

2022-03-09 07:10 UTC, 0xSachinK commented on contracts/protocol/modules/PerpV2BasisTradingModule.sol
> +        _setToken.calculateAndEditDefaultPosition(
Added in [2bafca2](https://github.com/SetProtocol/set-protocol-v2/pull/198/commits/2bafca23b9ca00e1d3899a61d00ffab68692606a)

2022-03-09 08:16 UTC, richardliang approved these changes

2022-03-09 09:32 UTC, merged